include:
  - board: nice_nano_v2
    shield: c_dux_left led_indicator
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: c_dux_right led_indicator
